### ISSUE TITLE
Change selectors names

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/redux-saga-thunk#17]
Per @Geczy's suggestion on https://github.com/diegohaz/redux-saga-thunk/pull/16#issuecomment-315548547, I agree with renaming selectors. I just think the current names should be kept as aliases (something like `export const hasFailed = failed`).

**Comment by jordanmkoncz** [comment]
So @Geczy was suggesting "pending, failed, done, complete". Personally I think "done" and "complete" are synonyms so it doesn't make sense that one of them represents "success" (versus "failure") and the other represents "finished" (i.e. "success" *or* "failure"), when in English they essentially mean the same thing.

I suggest the following selector names: 

* `pending` - the request is currently taking place, i.e. loading
* `complete` - the request is finished (i.e. it has failed or succeeded)
* `failure` - the request failed
* `success` - the request succeeded

I think these fairly work well in a sentence when you put them in the context of what they represent:

* "The request is pending."
* "The request is complete."
* "The request's status is failure."
* "The request's status is success."

Alternatively I think `failed` and `succeeded` would also be fine (and you'd use `completed` instead of `complete`), but `succeeded` is just a bit harder to type than `success`.

**Comment by Geczy** [comment]
We could also copy the promise statuses

https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Pending
Fulfilled
Rejected

**Comment by diegohaz** [comment]
I vote for `pending`, `fulfilled`, `rejected` and `done`.

**Comment by jordanmkoncz** [comment]
@diegohaz I think those names are good, nice to have them correspond with the Promise statuses too.

**Comment by vegeta897** [comment]
`done` vs. `complete` had me puzzled; it wasn't apparent to me that `done` meant success (or, not failure). Copying the `Promise` statuses sounds like a good change.
